---
title: NBA Playoff Efficiency Overview
author: Sebastian Pycior
date: '2019-04-25'
slug: nba-playoff-efficiency-overview
categories: []
tags: []
description: ''
topics: []
---




```{r include=FALSE}
library(ggiraphExtra)
library(ggiraph)
library(ggplot2)
library(hrbrthemes)
library(DT)

total_1_po_only<-read.csv("/Users/sebastianpycior/sebasportfolio/content/post/total_1_po_only.csv", stringsAsFactors = FALSE, header = TRUE)
total_1_po_only_curr<-read.csv("/Users/sebastianpycior/sebasportfolio/content/post/total_1_po_only_curr.csv", stringsAsFactors = FALSE, header = TRUE)
total_1_champs<-read.csv("/Users/sebastianpycior/sebasportfolio/content/post/total_1_champs.csv", stringsAsFactors = FALSE, header = TRUE)
total_1_po_only_currd<-read.csv("/Users/sebastianpycior/sebasportfolio/content/post/total_1_po_only_currd.csv", stringsAsFactors = FALSE, header = TRUE)



total_1_po_only$tooltip <- c(paste0("Team = ", total_1_po_only$TeamSeason, "\n SODD = ", round(total_1_po_only$Off_Deff_Diff, digits = 2)))
tooltip_css <- "background-color:white;font-style:normal;padding:10px;border-radius:10px 20px 10px 20px;"
```
Efficiency data [available here on ESPN.](http://www.espn.com/nba/hollinger/teamstats).

```{r echo=FALSE}
g<-ggplot(total_1_po_only, aes(total_1_po_only$Off_Deff_Diff,total_1_po_only$PlayoffGames)) + 
  geom_point(data=total_1_po_only_curr, aes(total_1_po_only_curr$Off_Deff_Diff,total_1_po_only_curr$PlayoffGames), colour="green", size=3)+
  geom_point(data=total_1_champs, aes(total_1_champs$Off_Deff_Diff,total_1_champs$PlayoffGames), colour="blue", size=3)+
  geom_point_interactive(aes(tooltip = total_1_po_only$tooltip, data_id = TeamSeason), alpha = 1/10, size=3)+
  geom_vline_interactive(aes(xintercept = mean(total_1_champs$Off_Deff_Diff),
                             tooltip = paste0("Mean SODD of NBA Champs since 2002-03: ",round(mean(total_1_champs$Off_Deff_Diff), 2)),
                             data_id = Off_Deff_Diff),size=.5, color = "mediumorchid1", alpha =1/3)+
  ggtitle("SODD of NBA Playoff teams", subtitle = "")+
  labs(caption = "Data: ESPN, nbastatR, Viz: @Sebasp41, ggiraph",
       x = "Regular Season Offensive Efficiency minus Deffensive Efficiency",
       y = "Playoff Game Appearances")+
  theme_ipsum(plot_title_face = "plain",
              axis_text_size = 14, caption_size = 10,axis_title_size = 12)
ggiraph(code = {print(g)}, tooltip_extra_css = tooltip_css, tooltip_opacity = .85 )
```

```{r echo=FALSE}
total_1_po_only_currd<-subset(total_1_po_only_currd, select = c(2:5))
datatable(total_1_po_only_currd)
```

