---
title: NBA - Plotly BMI and Speed Overview
author: Sebastian Pycior
date: '2019-10-16'
slug: nba-plotly-bmi-and-speed-overview
categories: []
tags: []
description: ''
topics: []
---


```{r, include=FALSE}
htwt_double<-read.csv("/Users/sebastianpycior/sebasportfolio/content/post/htwt_double.csv", header = TRUE, stringsAsFactors = FALSE)

htwt_double <- htwt_double[order(htwt_double$Team),]
```





```{r, echo=FALSE}
library(plotly)    

p <- htwt_double %>%
  plot_ly(
    type = 'scatter', 
    x = ~Wt.kg, 
    y = ~Ht.m,
    text = ~paste("Player: ", Name,'<br>Pos.:', Pos., '<br>Height:', Ht.m, 'm', '<br>Weight:', Wt.kg, 'kg', '<br>BMI:', BMI),
    color = ~Team,
   colors =  c("#1D4289",
               "#E03A3E",
               "#007A33",
               "#1D1160",
               "#CE1141",
               "#6F263D",
               "#00538C",
               "#0E2240",
               "#C8102E",
               "#1D428A",
               "#CE1141",
               "#002D62",
               "#C8102E",
               "#552583",
               "#5D76A9",
               "#98002E",
               "#00471B",
               "#0C2340",
               "#0C2340",
               "#F58426",
               "#EF3B24",
               "#0077C0",
               "#006BB6",
               "#1D1160",
               "#E03A3E",
               "#5A2D81",
               "#C4CED4",
               "#B4975A",
               "#753BBD",
               "#002B5C"),
    hoverinfo = 'text',
    mode = 'markers', 
    transforms = list(
      list(
        type = 'filter',
        target = ~Team,
        operation = '=',
        value = unique(htwt_double$Team)[1]
      )
    )) %>% layout(
      showlegend = FALSE,
      updatemenus = list(
        list(
          type = 'dropdown',
          active = 0,
          buttons =list(
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[1]),
                 label = unique(htwt_double$Team)[1]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[2]),
                 label = unique(htwt_double$Team)[2]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[3]),
                 label = unique(htwt_double$Team)[3]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[4]),
                 label = unique(htwt_double$Team)[4]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[5]),
                 label = unique(htwt_double$Team)[5]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[6]),
                 label = unique(htwt_double$Team)[6]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[7]),
                 label = unique(htwt_double$Team)[7]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[8]),
                 label = unique(htwt_double$Team)[8]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[9]),
                 label = unique(htwt_double$Team)[9]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[10]),
                 label = unique(htwt_double$Team)[10]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[11]),
                 label = unique(htwt_double$Team)[11]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[12]),
                 label = unique(htwt_double$Team)[12]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[13]),
                 label = unique(htwt_double$Team)[13]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[14]),
                 label = unique(htwt_double$Team)[14]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[15]),
                 label = unique(htwt_double$Team)[15]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[16]),
                 label = unique(htwt_double$Team)[16]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[17]),
                 label = unique(htwt_double$Team)[17]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[18]),
                 label = unique(htwt_double$Team)[18]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[19]),
                 label = unique(htwt_double$Team)[19]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[20]),
                 label = unique(htwt_double$Team)[20]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[21]),
                 label = unique(htwt_double$Team)[21]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[22]),
                 label = unique(htwt_double$Team)[22]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[23]),
                 label = unique(htwt_double$Team)[23]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[24]),
                 label = unique(htwt_double$Team)[24]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[25]),
                 label = unique(htwt_double$Team)[25]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[26]),
                 label = unique(htwt_double$Team)[26]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[27]),
                 label = unique(htwt_double$Team)[27]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[28]),
                 label = unique(htwt_double$Team)[28]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[29]),
                 label = unique(htwt_double$Team)[29]),
            list(method = "restyle",
                 args = list("transforms[0].value", unique(htwt_double$Team)[30]),
                 label = unique(htwt_double$Team)[30])
          )
        )
      )
    )
p

```

